name: Deploy to IBM Cloud Foundry

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud plugin install cloud-foundry -f

      - name: IBM Cloud Login
        run: |
          ibmcloud login --apikey "${{ secrets.IBM_CLOUD_API_KEY }}" -r eu-de
          ibmcloud target --cf

      - name: Push app to Cloud Foundry
        run: ibmcloud cf push
